name: "FoxESS PV Inverter"
version: "1.0.1"
slug: "foxess_t_series_integration"
description: "FoxESS T-Series PV inverter MQTT integration with Home Assistant"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
startup: services
boot: auto
options:
  inverter_ip: "192.168.1.31"
  inverter_port: 502
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mqtt_username"
  mqtt_password: "mqtt_password"
schema:
  inverter_ip: str
  inverter_port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
